import { TRUSTED_BROWSER_RUNTIME_BOUNDARY_HEADER } from "./browser-runtime-boundary.js"

export function browserRuntimeWorkerSource(
  bundle: string,
  bundleSpecifiers: readonly string[],
): string {
  const specifiers = [...new Set([
    ...bundleSpecifiers,
    "node:buffer",
    "node:readline",
    "node:vm",
  ])].sort()
  const imports = specifiers.map((specifier, index) =>
    `import * as dependency${index} from ${JSON.stringify(specifier)}`)
  const dependencies = specifiers.map((specifier, index) =>
    `  [${JSON.stringify(specifier)}, dependency${index}],`)
  return [
    TRUSTED_BROWSER_RUNTIME_BOUNDARY_HEADER.trimEnd(),
    ...imports,
    "",
    `const BUNDLE_SOURCE = ${JSON.stringify(bundle)}`,
    "const MAX_REQUEST_BYTES = 1024 * 1024",
    "const hostProcess = process",
    "const dependencyMap = new Map([",
    ...dependencies,
    "])",
    "const requireFromMap = (specifier) => {",
    "  if (typeof specifier !== 'string' || !dependencyMap.has(specifier)) {",
    "    throw new Error('Browser worker requested an unverified module')",
    "  }",
    "  return dependencyMap.get(specifier)",
    "}",
    "const safeProcess = Object.freeze({",
    "  arch: hostProcess.arch,",
    "  env: Object.freeze({ ...hostProcess.env }),",
    "  nextTick: hostProcess.nextTick.bind(hostProcess),",
    "  off: hostProcess.off.bind(hostProcess),",
    "  on: hostProcess.on.bind(hostProcess),",
    "  once: hostProcess.once.bind(hostProcess),",
    "  platform: hostProcess.platform,",
    "  removeListener: hostProcess.removeListener.bind(hostProcess),",
    "  stderr: hostProcess.stderr,",
    "  stdin: hostProcess.stdin,",
    "  stdout: hostProcess.stdout,",
    "  version: hostProcess.version,",
    "  versions: Object.freeze({ ...hostProcess.versions }),",
    "})",
    "const bufferModule = dependencyMap.get('node:buffer')",
    "const vmModule = dependencyMap.get('node:vm')",
    "const readlineModule = dependencyMap.get('node:readline')",
    "if (!bufferModule || !vmModule || !readlineModule) throw new Error('Browser worker bootstrap dependencies are absent')",
    "const sandbox = Object.create(null)",
    "Object.assign(sandbox, {",
    "  AbortController, AbortSignal, Array, ArrayBuffer, Atomics, BigInt, BigInt64Array,",
    "  BigUint64Array, Blob, Boolean, Buffer: bufferModule.Buffer, DataView, Date,",
    "  DOMException, Error, EvalError, Event, EventTarget, FinalizationRegistry, Float32Array,",
    "  Float64Array, FormData, Headers, Int8Array, Int16Array, Int32Array, Intl, JSON, Map,",
    "  Math, MessageChannel, MessageEvent, MessagePort, Number, Object, Performance, Promise,",
    "  RangeError, ReadableStream, ReferenceError, Reflect, RegExp, Request, Response, Set,",
    "  SharedArrayBuffer, String, Symbol, SyntaxError, TextDecoder, TextEncoder, TransformStream,",
    "  TypeError, URIError, URL, URLSearchParams, Uint8Array, Uint8ClampedArray, Uint16Array,",
    "  Uint32Array, WeakMap, WeakRef, WeakSet, WebSocket, WritableStream, atob, btoa, clearImmediate,",
    "  clearInterval, clearTimeout, console, crypto, fetch, performance, process: safeProcess,",
    "  queueMicrotask, setImmediate, setInterval, setTimeout, structuredClone,",
    "})",
    "const context = vmModule.createContext(sandbox, {",
    "  codeGeneration: { strings: true, wasm: false },",
    "  name: 'opencode-cycle-browser-worker',",
    "})",
    "const wrapper = new vmModule.Script(`(function(require,module,exports){${BUNDLE_SOURCE}\\n})`, {",
    "  filename: 'managed-browser-worker.bundle.cjs',",
    "}).runInContext(context, { timeout: 5000 })",
    "const cjsModule = { exports: {} }",
    "wrapper(requireFromMap, cjsModule, cjsModule.exports)",
    "const Factory = cjsModule.exports.ManagedBrowserSessionFactory",
    "if (typeof Factory !== 'function') throw new Error('Browser worker export is invalid')",
    "let session",
    "let closing = false",
    "const respond = (id, value, errorClass) => new Promise((resolve) => {",
    "  const record = errorClass === undefined ? { id, ok: true, value } : { errorClass, id, ok: false }",
    "  hostProcess.stdout.write(`${JSON.stringify(record)}\\n`, resolve)",
    "})",
    "const handle = async (request) => {",
    "  if (!request || typeof request !== 'object' || !Number.isSafeInteger(request.id) ||",
    "    typeof request.method !== 'string') throw new Error('Browser worker request is invalid')",
    "  switch (request.method) {",
    "    case 'initialize': {",
    "      if (session !== undefined || !request.value || typeof request.value !== 'object') {",
    "        throw new Error('Browser worker initialization is invalid')",
    "      }",
    "      const options = request.value.options",
    "      const input = request.value.input",
    "      if (!options || !input || !Array.isArray(input.allowedOrigins)) {",
    "        throw new Error('Browser worker initialization payload is invalid')",
    "      }",
    "      const factory = new Factory(options)",
    "      session = await factory.create({ ...input, allowedOrigins: new Set(input.allowedOrigins) })",
    "      return { status: 'ready' }",
    "    }",
    "    case 'allowOrigin':",
    "      if (!session || !request.value || typeof request.value.origin !== 'string') {",
    "        throw new Error('Browser worker allowOrigin request is invalid')",
    "      }",
    "      session.allowOrigin(request.value.origin)",
    "      return { status: 'allowed' }",
    "    case 'execute':",
    "      if (!session) throw new Error('Browser worker session is absent')",
    "      return session.execute(request.value)",
    "    case 'close': {",
    "      if (!session) return { status: 'closed' }",
    "      const value = await session.close()",
    "      session = undefined",
    "      closing = true",
    "      return value",
    "    }",
    "    default:",
    "      throw new Error('Browser worker method is unsupported')",
    "  }",
    "}",
    "const reader = readlineModule.createInterface({ crlfDelay: Infinity, input: hostProcess.stdin })",
    "let queue = Promise.resolve()",
    "reader.on('line', (line) => {",
    "  queue = queue.then(async () => {",
    "    if (Buffer.byteLength(line, 'utf8') > MAX_REQUEST_BYTES) throw new Error('Browser worker request is too large')",
    "    let request",
    "    try { request = JSON.parse(line) } catch { throw new Error('Browser worker request JSON is invalid') }",
    "    try {",
    "      const value = await handle(request)",
    "      await respond(request.id, value)",
    "      if (closing) setImmediate(() => hostProcess.exit(0))",
    "    } catch (error) {",
    "      const errorClass = error instanceof Error && /^[A-Za-z][A-Za-z0-9]*$/.test(error.name)",
    "        ? error.name : 'Error'",
    "      await respond(request.id, undefined, errorClass)",
    "    }",
    "  }).catch(() => hostProcess.exit(1))",
    "})",
    "reader.on('close', () => {",
    "  queue.finally(async () => {",
    "    try { await session?.close() } finally { hostProcess.exit(0) }",
    "  })",
    "})",
    "",
  ].join("\n")
}

export function browserRuntimeClientSource(): string {
  return [
    'import { spawn } from "node:child_process"',
    'import { createInterface } from "node:readline"',
    'import { fileURLToPath } from "node:url"',
    "",
    'const WORKER_PATH = fileURLToPath(import.meta.resolve("./managed-browser-worker.mjs"))',
    "const MAX_PROTOCOL_BYTES = 1024 * 1024",
    "class WorkerTransport {",
    "  constructor(options, input) { this.options = options; this.input = input; this.nextId = 0; this.pending = new Map(); this.closed = false }",
    "  async open() {",
    "    const environment = { ...process.env }",
    "    if (process.versions.electron) environment.ELECTRON_RUN_AS_NODE = '1'",
    "    this.child = spawn(process.execPath, [WORKER_PATH], { env: environment, stdio: ['pipe', 'pipe', 'pipe'], windowsHide: true })",
    "    this.exited = new Promise((resolve) => this.child.once('exit', (code) => { this.closed = true; for (const item of this.pending.values()) item.reject(new Error('Managed browser worker exited')); this.pending.clear(); resolve(code ?? 1) }))",
    "    this.child.once('error', () => { for (const item of this.pending.values()) item.reject(new Error('Managed browser worker failed')); this.pending.clear() })",
    "    let stderrBytes = 0",
    "    this.child.stderr.on('data', (value) => { stderrBytes += value.length; if (stderrBytes > 64 * 1024) this.child.kill() })",
    "    const lines = createInterface({ crlfDelay: Infinity, input: this.child.stdout })",
    "    lines.on('line', (line) => this.receive(line))",
    "    await this.request('initialize', {",
    "      input: { ...this.input, allowedOrigins: [...this.input.allowedOrigins] },",
    "      options: this.options,",
    "    })",
    "  }",
    "  receive(line) {",
    "    if (Buffer.byteLength(line, 'utf8') > MAX_PROTOCOL_BYTES) { this.child.kill(); return }",
    "    let value",
    "    try { value = JSON.parse(line) } catch { this.child.kill(); return }",
    "    if (!value || !Number.isSafeInteger(value.id) || typeof value.ok !== 'boolean') { this.child.kill(); return }",
    "    const item = this.pending.get(value.id)",
    "    if (!item) { this.child.kill(); return }",
    "    this.pending.delete(value.id)",
    "    if (value.ok) item.resolve(value.value)",
    "    else item.reject(new Error('Managed browser worker request failed'))",
    "  }",
    "  request(method, value) {",
    "    if (this.closed || !this.child?.stdin.writable) return Promise.reject(new Error('Managed browser worker is unavailable'))",
    "    const id = this.nextId++",
    "    const line = `${JSON.stringify({ id, method, value })}\\n`",
    "    if (Buffer.byteLength(line, 'utf8') > MAX_PROTOCOL_BYTES) return Promise.reject(new Error('Managed browser worker request is too large'))",
    "    return new Promise((resolve, reject) => {",
    "      this.pending.set(id, { reject, resolve })",
    "      this.child.stdin.write(line, (error) => { if (error) { this.pending.delete(id); reject(new Error('Managed browser worker write failed')) } })",
    "    })",
    "  }",
    "  async finish() {",
    "    this.child?.stdin.end()",
    "    const code = await Promise.race([this.exited, new Promise((resolve) => setTimeout(() => resolve('timeout'), 5000))])",
    "    if (code === 'timeout') { this.child?.kill(); await this.exited }",
    "  }",
    "}",
    "export class ManagedBrowserSessionFactory {",
    "  constructor(options) { this.options = options }",
    "  async create(input) { const transport = new WorkerTransport(this.options, input); await transport.open(); return new WorkerSession(transport) }",
    "}",
    "class WorkerSession {",
    "  constructor(transport) { this.transport = transport; this.barrier = Promise.resolve(); this.closed = false }",
    "  allowOrigin(origin) { this.barrier = this.barrier.then(() => this.transport.request('allowOrigin', { origin })); this.barrier.catch(() => undefined) }",
    "  async execute(command) { if (this.closed) throw new Error('Managed browser session is closed'); await this.barrier; return this.transport.request('execute', command) }",
    "  async close() { if (this.closed) return { status: 'closed' }; this.closed = true; await this.barrier; try { return await this.transport.request('close') } finally { await this.transport.finish() } }",
    "}",
    "",
  ].join("\n")
}
